Ensure no response is sent to one way commands
eclipse-kanto/suite-bootstrapping pull request #27
Opened 2022-11-03 12:14 UTC by gabriela-yoncheva

[#20] Improper request data sent when no pre-bootstrapping data is provided Suite bootstrapping service gets disconnected after receiving an error response

Problem found:
- Sending a response to a command was determined by correlation-id instead of the response-required header, an EOF error, which caused the connection to drop, was caused by the service trying to reply to one-way commands.

Fixes applied:
- Ensured no reply is sent to messages that don't require a response.

Further actions needed:
- Updating the software update, system metrics, file upload and backup services accordingly to avoid similar issues

Signed-off-by: Gabriela Yoncheva <Gabriela.Yoncheva@bosch.io>

2022-11-07 09:24 UTC, e-grigorov requested changes

2022-11-07 09:24 UTC, e-grigorov commented on internal/bootstrapping/agent.go
>  	var replyToID string
It seems that this variable is not needed any more. The correlation identifier can be provided.

2022-11-07 09:24 UTC, e-grigorov commented on internal/bootstrapping/agent.go
> +	if respReq && len(correlationID) > 0 {
If the replyToID is removed, we don't need this logic. Even more, it doesn't seem to be redundant.

2022-11-07 09:24 UTC, e-grigorov commented on internal/bootstrapping/agent.go
> +func (a *Agent) handleResponseMessage(msg *message.Message) (string, *MessageError, bool, error) {
`string, *MessageError, bool, error` - is it the right order? There are: string, msg error, bool, error. The boolean is somehow like a gap between the two errors.

2022-11-10 11:45 UTC, e-grigorov requested changes

2022-11-10 11:45 UTC, e-grigorov commented on internal/bootstrapping/agent.go
> +				return "", respReq, NewMessageParameterInvalidError(), errors.Wrapf(err, "invalid payload: %v", rspMsg.Value)
I guess that the correlation id should be used here.

2022-11-11 10:17 UTC, e-grigorov commented on internal/bootstrapping/agent.go
> +	return correlationID, respReq, nil, nil
Isn't it an error situation? Basically, this means that the bootstrapping receives a message which is not addressed to the correct device or path is wrong. In this case, the message should be ignored. Currently, we can send a response.

2022-11-11 11:03 UTC, hristobojilov approved these changes

2022-11-17 14:23 UTC, e-grigorov approved these changes

2022-11-17 14:24 UTC, merged