Provide integration tests for the key functionalities
eclipse-kanto/suite-bootstrapping pull request #32
Opened 2023-04-03 09:02 UTC by antonia-avramova

[#19] Provide integration tests for the key functionalities

Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>

2023-04-04 09:28 UTC, antoniyatrifonova requested changes

2023-04-04 09:28 UTC, antoniyatrifonova commented on integration/bootstrapping_test.go
> +	bootstrappingThingURL   string
You don't need it, remove it

2023-04-04 09:28 UTC, antoniyatrifonova commented on integration/bootstrapping_test.go
> +		defer suite.TearDown()
You don't need the defer. Please, review the use of defer in all places

2023-04-06 11:20 UTC, antoniyatrifonova approved these changes

2023-04-12 10:37 UTC, k-gostev requested changes
couple of nits

2023-04-12 10:37 UTC, k-gostev commented on integration/bootstrapping_test.go
> +	suiteConnector                     = "suite-connector.service"
align it with the constant above, eg. `scServiceName` or `suiteConnectorServiceName`

2023-04-12 10:37 UTC, k-gostev commented on integration/bootstrapping_test.go
> +	}
```suggestion
		require.NoError(t, err, "cannot get thing configuration")
```

2023-04-12 10:37 UTC, k-gostev commented on integration/util.go
> +func getBootstrapConfigStruct(path string) (util.BootstrapConfiguration, error) {
you can use pointer here in order to return `nil, err` on error.
```suggestion
func getBootstrapConfigStruct(path string) (*util.BootstrapConfiguration, error) {
```

2023-04-12 10:37 UTC, k-gostev commented on integration/util.go
> +	}
```suggestion	
	if err := json.Unmarshal(content, &cfg); err != nil {
		return cfg, fmt.Errorf("unable to unmarshal to json: %v", err)
	}
```

2023-04-12 10:37 UTC, k-gostev commented on integration/util.go
> +	cfg *util.ConnectorConfiguration, requestID string) (map[string]interface{}, error) {
```suggestion
func createBootstrappingResponsePayload(cfg *util.ConnectorConfiguration, requestID string) (map[string]interface{}, error) {
```

2023-04-24 05:42 UTC, k-gostev approved these changes

2023-04-24 11:33 UTC, antoniyatrifonova approved these changes

2023-04-24 11:37 UTC, merged