Update Eclipse Paho to version 1.4.1
eclipse-kanto/suite-bootstrapping pull request #9
Opened 2022-08-22 16:38 UTC by antonia-avramova

[#8] Update Eclipse Paho to version 1.4.1

Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>

2022-08-22 20:15 UTC, e-grigorov commented
@antonia-avramova The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances :blush: 

Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

2022-08-22 20:41 UTC, e-grigorov requested changes

2022-08-22 20:41 UTC, e-grigorov commented on NOTICE.md
> +golang.org/x/sync (v0.0.0-20210220032951-036812b2e83c)
There is no strict rule but it'll be more readable to keep the current order. I would suggest to move golang.org/x/sync between golang.org/x/net and golang.org/x/sys.

2022-08-23 06:20 UTC, antonia-avramova commented
> @antonia-avramova The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).
> 
> This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances 😊
> 
> Please, provide your feedback as a comment here that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

I understand and agree with the license change explained above.

2022-08-23 07:48 UTC, e-grigorov approved these changes

2022-08-23 07:51 UTC, merged